version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest # TODO: update later with non local version
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  flask-backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      AWS_ENDPOINT_URL: http://dynamodb-local:8000
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    depends_on:
      - dynamodb-local
    volumes:
      - ./backend:/app

  react-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - flask-backend
    volumes:
      - ./frontend/src:/app/src